#!/bin/sh -e

DB_TPL=articles.db~dist
DB_DIR=/mnt/db
DB_NAME=articles.db

cd /var/www/scatbay.com/_articles/var/db

DB_FILE="$DB_DIR/$DB_NAME"

[ -f "$DB_FILE" ] || cp "$DB_TPL" "$DB_FILE"

chown -R nobody:nobody "$DB_DIR"
chmod 0600 "$DB_FILE"

[ -f "$DB_NAME" ] || ln -s "$DB_FILE" .
