#!/bin/sh -e

DB_TPL=/var/www/scatbay.com/_articles/var/db/articles.db~dist
DB_FILE=/mnt/db/articles.db

[ -f "$DB_FILE" ] || cp "$DB_TPL" "$DB_FILE"

chown nobody:nobody "$DB_FILE"
chmod 0600 "$DB_FILE"

DB_LINK=`dirname "$DB_TPL"``basename "$DB_FILE"`

[ -f "$DB_LINK" ] || ln -s "$DB_FILE" "$DB_LINK"
